# Generated by Django 4.2.16 on 2024-10-08 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gerenciamento', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='motorista',
            name='cpf_motorista',
        ),
        migrations.AddField(
            model_name='motorista',
            name='cpf_motorista',
            field=models.CharField(blank=True, max_length=11, null=True, unique=True),
        ),
    ]
