# Generated by Django 4.2.16 on 2024-11-19 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gerenciamento', '0002_remove_motorista_cpf_motorista_cpf_motorista'),
    ]

    operations = [
        migrations.CreateModel(
            name='Acessa',
            fields=[
                ('data_alteracao', models.DateTimeField(primary_key=True, serialize=False)),
                ('valor_km', models.DecimalField(decimal_places=2, max_digits=9)),
                ('valor_tonelada', models.DecimalField(decimal_places=2, max_digits=9)),
                ('valor_entrega', models.DecimalField(decimal_places=2, max_digits=12)),
            ],
            options={
                'db_table': 'acessa',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Carga',
            fields=[
                ('codigo_carga', models.AutoField(primary_key=True, serialize=False)),
                ('peso', models.DecimalField(decimal_places=2, max_digits=9)),
                ('valor_carga', models.DecimalField(decimal_places=2, max_digits=12)),
            ],
            options={
                'db_table': 'carga',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Entrega',
            fields=[
                ('id_entrega', models.AutoField(primary_key=True, serialize=False)),
                ('peso_entrega', models.DecimalField(decimal_places=2, max_digits=9)),
                ('valor_entrega', models.DecimalField(decimal_places=2, max_digits=12)),
                ('cidade', models.CharField(max_length=30)),
                ('dificuldade', models.BooleanField()),
                ('cliente', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'entrega',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EntregaDistribuidora',
            fields=[
                ('distribuidora', models.CharField(max_length=30, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'entrega_distribuidora',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Pagamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taxa_desconto', models.DecimalField(decimal_places=2, max_digits=8)),
                ('taxa_acrescimo', models.DecimalField(decimal_places=2, max_digits=8)),
                ('valor_calculado', models.DecimalField(decimal_places=2, max_digits=12)),
                ('data_pagamento', models.DateTimeField()),
                ('status_pagamento', models.CharField(choices=[('PE', 'PENDENTE'), ('TR', 'EM_TRANSFERENCIA'), ('PA', 'PAGO')], default='PE', max_length=2)),
            ],
            options={
                'db_table': 'pagamento',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tipo',
            fields=[
                ('id_tipo', models.AutoField(primary_key=True, serialize=False)),
                ('nome_tipo', models.CharField(max_length=20)),
                ('capacidade_peso', models.DecimalField(decimal_places=2, max_digits=9)),
                ('quantidade_eixos', models.PositiveSmallIntegerField()),
            ],
            options={
                'db_table': 'tipo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Veiculo',
            fields=[
                ('renavam', models.CharField(max_length=11, primary_key=True, serialize=False)),
                ('placa', models.CharField(max_length=20)),
                ('marca', models.CharField(max_length=20)),
                ('modelo', models.CharField(max_length=20)),
                ('cor', models.CharField(max_length=20)),
                ('ano', models.DateField()),
            ],
            options={
                'db_table': 'veiculo',
                'managed': False,
            },
        ),
        migrations.AlterModelOptions(
            name='fiscal',
            options={'managed': False},
        ),
    ]
