# Generated by Django 4.2.16 on 2024-12-05 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gerenciamento', '0003_acessa_carga_entrega_entregadistribuidora_pagamento_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pagamento',
            options={'managed': True},
        ),
    ]
