# Generated by Django 4.2.16 on 2024-12-05 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gerenciamento', '0004_alter_pagamento_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pagamento',
            options={'managed': False},
        ),
    ]
